[container.image]
name="hello-api" # optional
tag="sample6"  # default is latest

[cloud.deployment.probes.readiness]
port=9090
path="/helloWorld/readyz"

[cloud.deployment.probes.liveness]
port=9090
path="/helloWorld/healthz"