[container.image]
repository="anuruddhal" # optional default is local
name="math" # optional
tag="sample3"  # default is latest

[cloud.deployment]
min_memory="100Mi" # optional
max_memory="256Mi" # optional
min_cpu="200m" # optional
max_cpu="500m" # optional
    [cloud.deployment.autoscaling]
        min_replicas=2
        max_replicas=5
        cpu=50