[container.image]
repository="anuruddhal"
name="hello-api"
tag="sample5"

[[cloud.config.maps]]
file="./conf/data.txt"
mount_path="/home/ballerina/data"

[[cloud.config.files]]
file="./conf/Config.toml"
name="sample5-config-map"
